### ISSUE TITLE
Question: function of the for loop in the trigger step

### ISSUE THREAD

**Issue by tomiszili** [aws-samples/aws-cloudformation-stackset-orchestration#3]
Hi!

What is the function of the for loop in [this](https://github.com/aws-samples/aws-cloudformation-stackset-orchestration/blob/main/lambda/01_trigger_step_function/app.py#L47-L50) file?

Thanks in advance for the clarification!

**Comment by sebiwi** [comment]
Hi tomiszili,

The purpose is to delete the stacksets when you set the `Terminate` flag to `True`.

See the **Usage** section of this blog post for more information about it: https://aws.amazon.com/fr/blogs/mt/aws-cloudformation-stackset-orchestration-automated-deployment-using-aws-step-functions/
